version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    links:
      - php
    networks:
      - pg-network
  
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
      args:
        - POSTGRES_PASSWORD=${PASSWORD}
        - POSTGRES_DB=${DATABASE}
        - POSTGRES_USER=${DBUSERNAME}
    ports:
      - "5433:5432"
    volumes:
      - ./docker/db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pg-network
  
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      - USERNAME=${DBUSERNAME}
      - PASSWORD=${PASSWORD}
      - HOST=${HOST}
      - DATABASE=${DATABASE}
    volumes:
      - .:/app
    networks:
      - pg-network
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - pg-network
  
networks:
  pg-network:

volumes:
  pg-data: